name: streambox_adapters
description: >
  Storage adapters for streambox_core: memory, SharedPrefs, secure storage.
version: 1.4.0
homepage: https://github.com/kalaganov/streambox_adapters
issue_tracker: https://github.com/kalaganov/streambox_core/issues
topics:
  - repository
  - caching
  - reactive
  - strategy
  - core

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: ^9.2.4 # https://pub.dev/packages/flutter_secure_storage
  meta: ^1.16.0 # https://pub.dev/packages/meta
  shared_preferences: ^2.5.3 # https://pub.dev/packages/shared_preferences
  streambox_core: ^1.4.0 # https://pub.dev/packages/streambox_core

dev_dependencies:
  test: ^1.26.2 # https://pub.dev/packages/test
  very_good_analysis: ^9.0.0 # https://pub.dev/packages/very_good_analysis
